[workspace]
members = ["components/cart", "components/pricing", "components/product", "components/order", "components/product-search"]
exclude = ["benchmark"]
resolver = "2"

[profile.release]
opt-level = "s"
lto = true
