[package]
name = "shopping-cart"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
strip = true

[dependencies]
once_cell = "1.17.1"
rand = "0.8.5"
wit-bindgen-rt = { version = "0.26.0", features = ["bitflags"] }
golem-rust = "1.1.0"
uuid = { version = "1.10.0", features = ["v4"] }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"golem:api" = { path = "wit/deps/golem" }
"golem:rpc" = { path = "wit/deps/wasm-rpc" }
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:io" = { path = "wit/deps/io" }
