package golem:product;

interface api {
  use wasi:clocks/wall-clock@0.2.0.{datetime};

  record product {
    product-id: string,
    name: string,
    brand: string,
    description: string,
    tags: list<string>,
    created-at: datetime,
    updated-at: datetime
  }

  initialize-product: func(name: string, brand: string, description: string, tags: list<string>);

  get: func() -> option<product>;
}

world product {

  export golem:api/save-snapshot@1.1.6;
  export golem:api/load-snapshot@1.1.6;

  export api;
}