package golem:product;

interface api {

  record product {
    product-id: string,
    name: string,
    description: string,
    tags: list<string>
  }

  initialize-product: func(name: string, description: string, tags: list<string>);

  get: func() -> option<product>;
}

world product {

  export golem:api/save-snapshot@1.1.6;
  export golem:api/load-snapshot@1.1.6;

  export api;
}