package golem: order;

interface api {

  enum order-status {
    new,
    shipped,
    cancelled,
  }

  record address {
    street1: string,
    street2: option<string>,
    city: string,
    state-or-region: string,
    country: string,
    postal-code: string,
    name: option<string>,
    business-name: option<string>,
    phone-number: option<string>
  }

  record order-item {
    product-id: string,
    name: string,
    price: float32,
    quantity: u32,
  }

  record order {
    order-id: string,
    user-id: string,
    order-status: order-status,
    items: list<order-item>,
    billing-address: option<address>,
    shipping-address: option<address>,
    total: float32,
    currency: string,
    timestamp: u64,
  }

  record create-order {
    user-id: string,
    items: list<order-item>,
    billing-address: option<address>,
    shipping-address: option<address>,
    total: float32,
    currency: string,
    timestamp: u64,
  }

  record product-not-found-error {
    message: string,
    product-id: string,
  }

  record pricing-not-found-error {
    message: string,
    product-id: string,
  }

  record address-not-valid-error {
    message: string,
  }


  record item-not-found-error {
    message: string,
    product-id: string,
  }

  record empty-items-error {
    message: string,
  }

  record billing-address-not-set-error {
    message: string,
  }

  record action-not-allowed-error {
    message: string,
    status: order-status,
  }

  variant error {
    product-not-found(product-not-found-error),
    pricing-not-found(pricing-not-found-error),
    address-not-valid(address-not-valid-error),
    item-not-found(item-not-found-error),
    empty-items(empty-items-error),
    action-not-allowed(action-not-allowed-error),
  }

  initialize-order: func(data: create-order) -> ();

  add-item: func(product-id: string, quantity: u32) -> result<_, error>;

  remove-item: func(product-id: string) -> result<_, error>;

  update-item-quantity: func(product-id: string, quantity: u32) -> result<_, error>;

  update-shipping-address: func(address: address) -> result<_, error>;

  update-billing-address: func(address: address) -> result<_, error>;

  ship-order: func() -> result<_, error>;

  cancel-order: func() -> result<_, error>;

  get: func() -> option<order>;
}

world order {
  import golem: pricing-stub/stub-pricing;
  import golem: product-stub/stub-product;

  import golem: api/host@0.2.0;

  export golem:api/save-snapshot@0.2.0;
  export golem:api/load-snapshot@0.2.0;

  export api;
}